<?php echo $this->doctype() . "\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <?php echo $this->headMeta() . "\n"; ?>
  <?php echo $this->headTitle(). "\n"; ?>
  <link rel="stylesheet" type="text/css" href="/css/login.css" />
  <script type="text/javascript" src="/js/jquery/jquery-1.7.1.min.js"></script>
  <script type="text/javascript" src="/js/login.js"></script>
</head>
<body>
  <?php echo $this->layout()->content ?>
</body>
</html>